### ISSUE TITLE
`cava_option_config` Reverts on waybar restart

### ISSUE THREAD

**Issue by Fort-P** [jvc84/wayves#1]
I seem to be unable to change any of the values in `cava_option_config`. I can edit the file, and save it, but restarting waybar to apply the changes reverts them in the file again. Took a brief look through the python, but didn't see anything that should be resetting it.

Additionally, it doesn't seem to support mixing and matching the various option, tried using `-o cat -i cava -a cava`, which didn't assign a player, and when I included the `-p cava` flag it defaulted back to the flat-line cava display.

**Comment by jvc84** [comment]
1.  I fixed cava script, should parse config correctly now
2.  Option `-p`/`--player` is supposed to set `mpris` player to track. You can check active mpris players with `playerctl -l `.  "Player" `cava` is internal placeholder and it cannot be used  in any cases, except `-a cava -i cava -o cava`. 

Your setup `-o cat -i cava -a cava` can work with real mpris player, for example: 
`-o cat -i cava -a cava -p io.bassi.Amberol`

**Comment by Fort-P** [comment]
Awesome! Yeah, wasn't sure about how the player worked, but my guess was playerctl, then I saw you assigned it to cava in the script, so gave it a try. Thanks so much!
